[package]
name = "hackathon"
version = "0.0.1"
edition = "2024" 

[dependencies]
# Using the testnet
Iota = { git = "https://github.com/iotaledger/iota.git", subdir = "crates/iota-framework/packages/iota-framework", rev = "testnet" }

[addresses]
hackathon = "0x0"
iota = "0x2"      
std = "0x1"       